In [2]:
# This script contains exercises on 
# manipulating arrays with numpy
import numpy as np
x = np.arange(0, 3**3)

#### 1. What is the length of x?

In [31]:
print(np.shape(x))

print(len(x))

(27,)
27


#### 2. How do you get the first value out of x?

In [ ]:
#print(x)
print(x[0])

0


#### 3. How do you get the last value out of x?

In [15]:
print(x[-1])

26


#### 4. How do you get the first 5 values out of x?

In [ ]:
print(x[0:5]) #meaning, indexing is NOT inclusive, zero to five doesn't include number 5

[0 1 2 3 4]


#### 5. What about the last 5 values of x?

In [27]:
print(x[22:27])

print(x[-5: ]) #leave it as nothing, if end at -1 then you are ending with the 2nd to last value b/c inclusive

[22 23 24 25 26]
[22 23 24 25 26]


#### 6. How do you get every other value out of x?

In [ ]:
print(x[0::2]) #this is the slice function, within brackets is [start:stop:step]

print(x[::2])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26]



#### 7. Get the first 9 values of x, and reshape them to a 3x3 matrix. Assign this matrix to the variable `y`

In [48]:
y = x[:9]
print(y)

#np.reshape?   #for information/documentation on the command
y.reshape(3,3)

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. How do you get the middle value out of y?

In [ ]:
y = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])

print(y[1, 1]) #for 1st row counting from zero, and 1st value counting from zero

4


#### 9. How do you get the first row out of y?

In [59]:
print(y[0])

[0 1 2]


#### 10. How do you get the first column out of y?

In [62]:
print(y[:,0])

[0 3 6]


#### 11. Reshape x into a 3x3x3 cube. Assign this to the variable `z`

In [ ]:
x = np.arange(0, 3**3)
print(x)

z = x.reshape(3,3,3)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#### 12. How do you get the "center" value from z?

In [71]:
z = np.array([
    [[ 0, 1, 2],
     [ 3, 4, 5],
     [ 6, 7, 8]],
    [[ 9,10,11],
     [12,13,14],
     [15,16,17]],
    [[18,19,20],
     [21,22,23],
     [24,25,26]]
])
# Your code here

print(z[1,1,1]) 

13



#### 13. How do you take the total sum of z?

In [ ]:
sum(sum(sum(z)))

z.sum() #this runs the numpy version not standard built in python sum function

np.sum(z) #many ways!

np.int64(351)


#### 14. How do you take the sum along the first dimension of z?

In [84]:
z.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

#### 15. How do you take the sum along the last dimension of z?

In [81]:
z.sum(axis=-1)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])